[project]
name = "pygmid"
dynamic = ["version"]
description = "A python 3 implementation of the gm/ID starter kit"
readme = "README.md"
requires-python = ">=3.11.9"
dependencies = [
    "auto-all>=1.4.1",
    "h5py>=3.16.0",
    "matplotlib>=3.10.8",
    "numpy>=2.4.4",
    "pandas>=3.0.2",
    "prettytable>=3.17.0",
    "psf-utils>=1.10",
    "pyutils",
    "scipy>=1.17.1",
    "tqdm>=4.67.3",
]

license = "Apache-2.0"
authors = [
    { name = "Cian Ó Domhnaill", email = "cian.odonnell@tyndall.ie" },
    { name = "Tiarnach Ó Riada" },
    { name = "Danylo Galach" },
]
urls = { "Homepage" = "https://github.com/madrasalach/pygmid", "Bug Tracker" = "https://github.com/madrasalach/pygmid/issues" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.scripts]
pygmid = "pygmid.__main__:_cli"

[tool.setuptools]
# Find packages under src/
[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
version = {attr = "pygmid.__version__"}

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

[tool.uv.workspace]
members = [
    "pygmid",
]

[tool.uv.sources]
pyutils = { git = "https://github.com/burnettlab/pyutils.git" }

[tool.uv]
package = true
